hand_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - FFJ1
    - FFJ2
    - FFJ3
    - FFJ4
    - LFJ1
    - LFJ2
    - LFJ3
    - LFJ4
    - LFJ5
    - MFJ1
    - MFJ2
    - MFJ3
    - MFJ4
    - RFJ1
    - RFJ2
    - RFJ3
    - RFJ4
    - THJ1
    - THJ2
    - THJ3
    - THJ4
    - THJ5
    - WRJ1
    - WRJ2
  constraints:
      goal_time: 10.0
      stopped_velocity_tolerance: 0.2
      FFJ1: {trajectory: 0.9, goal: 0.4}
      FFJ2: {trajectory: 0.9, goal: 0.4}
      FFJ3: {trajectory: 0.9, goal: 0.4}
      FFJ4: {trajectory: 0.9, goal: 0.4}
      LFJ1: {trajectory: 0.9, goal: 0.4}
      LFJ2: {trajectory: 0.9, goal: 0.4}
      LFJ3: {trajectory: 0.9, goal: 0.4}
      LFJ4: {trajectory: 0.9, goal: 0.4}
      MFJ1: {trajectory: 0.9, goal: 0.4}
      MFJ2: {trajectory: 0.9, goal: 0.4}
      MFJ3: {trajectory: 0.9, goal: 0.4}
      MFJ4: {trajectory: 0.9, goal: 0.4}
      RFJ1: {trajectory: 0.9, goal: 0.4}
      RFJ2: {trajectory: 0.9, goal: 0.4}
      RFJ3: {trajectory: 0.9, goal: 0.4}
      RFJ4: {trajectory: 0.9, goal: 0.4}
      THJ1: {trajectory: 0.9, goal: 0.4}
      THJ2: {trajectory: 0.9, goal: 0.4}
      THJ3: {trajectory: 0.9, goal: 0.4}
      THJ4: {trajectory: 0.9, goal: 0.4}
      THJ5: {trajectory: 0.9, goal: 0.4}
      WRJ1: {trajectory: 0.9, goal: 0.4}
      WRJ2: {trajectory: 0.9, goal: 0.4}
  stop_trajectory_duration: 1.0
    
